// backend/src/types/graph.ts
import { ValidNodeType } from '../config/constants';

/**
 * Defines the X and Y coordinates for a node on the React Flow canvas.
 */
export interface XYPosition {
  x: number;
  y: number;
}

/**
 * The custom data payload embedded inside every InfraZero node.
 * This holds both the UI state and the backend/WASM simulation properties.
 */
export interface NodeData {
  label: string;
  type: ValidNodeType; // Strictly typed to the constants array (e.g., 'Gateway', 'PostgreSQL')
  isActive: boolean;
  
  // Optional hardware properties for the WASM simulation engine
  processingPowerMs?: number;
  coldStartLatencyMs?: number;
  failureRatePercent?: number;
  recoveryTimeMs?: number;
}

/**
 * Represents a Node in the architecture topology.
 * Maps exactly to React Flow's expected Node structure to prevent rendering crashes.
 */
export interface CustomNode {
  id: string;
  type: 'custom'; // Strictly enforced so React Flow uses your custom React UI component
  position: XYPosition;
  data: NodeData;
  
  // Optional React Flow specific UI properties
  width?: number;
  height?: number;
  selected?: boolean;
}

/**
 * Represents a connection (Edge) between two Nodes.
 * Maps exactly to React Flow's expected Edge structure.
 */
export interface CustomEdge {
  id: string;
  source: string;       // ID of the origin node
  target: string;       // ID of the destination node
  sourceHandle?: string; // The specific connection port (e.g., 'bottom')
  targetHandle?: string; // The specific connection port (e.g., 'top')
  
  // Optional network properties for the WASM simulation engine
  latencyMs?: number;
  jitterMs?: number;
  packetLossPercent?: number;
  bandwidthLimitMbps?: number;
  
  // Optional React Flow styling properties
  animated?: boolean;
  type?: 'default' | 'straight' | 'step' | 'smoothstep'; 
}

/**
 * The complete Architecture payload generated by the AI 
 * and saved/loaded from the Supabase database.
 */
export interface GraphTopology {
  nodes: CustomNode[];
  edges: CustomEdge[];
}